default:
  target: dev
  outputs:

    dev:
      type: bigquery
      method: service-account
      project: demoproject-301108
      dataset: demo_dataset
      keyfile: ./creds.json
      threads: 4
      timeout_seconds: 600
      location: asia-south1 # Optional, one of US or EU
      priority: interactive
      retries: 1
