name: dbt

on:
  push:
    branches:
      - master

env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT: demoproject-301108
  DBT_GOOGLE_BIGQUERY_DATASET: demoproject-301108:demo_dataset
  DBT_GOOGLE_BIGQUERY_KEYFILE: .github/workflows/demoproject-301108-8142ac59f026.json

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: mwhitaker/dbt-action@v0.1.3
      - run: dbt run
      - run: dbt test

{# demo test #}