name: dbt

on:
  push:
    branches:
      - master

env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT: your-gcp-project-id
  DBT_GOOGLE_BIGQUERY_DATASET: bigquery-dataset-id
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./.gcloud/dbt-service-account.json

jobs:
  dbt:
    - name: dbt action
      uses: mwhitaker/dbt-action@v0.1.3